import './globals.css'

export const metadata = {
  title: 'Craytivo Site',
  description: 'A minimal Next.js site generated by Copilot',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
